services:
  banco:
    image: postgres:16
    container_name: postgres-blog
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blog

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: blog-api
    restart: always

    depends_on:
      banco:
        condition: service_healthy

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://postgres:123456@banco:5432/blog
      PORT: 3000

    command: sh -c "npx prisma db push --accept-data-loss && npm start"

  frontend:
    build:
      context: ./frontend
    container_name: blog-frontend
    restart: always

    depends_on:
      - api

    ports:
      - "8080:80"

volumes:
  postgres_data: